### ISSUE TITLE
classroom_classroom_users table empty

### ISSUE THREAD

**Issue by GeekHamza1** [mishrakeshav/Open-Classroom#2]
hey !
students can join classrooms but the table classroom_classroom_users still empty ? how its this happend ?

**Comment by mishrakeshav** [comment]
if you want to access all the students of classrooms, then you may use classroom_users. or try to use classroom.users

**Comment by GeekHamza1** [comment]
i want insert all student to specific classroom via mysql  
i  already inseted them to mysql but its not showing in the website

**Comment by mishrakeshav** [comment]
Hey, I haven't looked into it. If you found a solution to this please describe it over here. :)

**Comment by GeekHamza1** [comment]
resolved !

**Comment by GeekHamza1** [comment]
i have pushed the soulution https://github.com/mishrakeshav/Open-Classroom/pull/4  https://github.com/mishrakeshav/Open-Classroom/pull/3
